/* AUTO-GENERATED by scripts/sync-ws-types.sh — DO NOT EDIT.\n   Source: backend/src/agent/transport/ws_messages.py */

export type Type = "auth";
export type UserId = string;
export type InviteCode = string | null;
export type Type1 = "list_sessions";
export type Type2 = "delete_session";
export type ThreadId = string;
export type Type3 = "get_session_state";
export type ThreadId1 = string;
export type Type4 = "reorder_edge";
export type ThreadId2 = string;
export type EdgeId = string;
export type Direction = "up" | "down";
export type Type5 = "create_edge";
export type ThreadId3 = string;
export type Source = string;
export type Target = string;
export type Type6 = "delete_edge";
export type ThreadId4 = string;
export type EdgeId1 = string;
export type Type7 = "update_position";
export type ThreadId5 = string;
export type NodeId = string;
export type X = number;
export type Y = number;
export type Type8 = "review_node";
export type ThreadId6 = string;
export type NodeId1 = string;
export type Action = "approve" | "reject";
export type Feedback = string | null;
export type Type9 = "execute_node";
export type ThreadId7 = string;
export type NodeId2 = string;
export type NodeType = "script" | "image" | "video" | "composite";
export type Description = string;
export type ImageGenProvider = string | null;
export type Duration = number | null;
export type Resolution = string | null;
export type GenerateAudio = boolean | null;
export type Type10 = "update_node_status";
export type ThreadId8 = string;
export type NodeId3 = string;
export type NodeStatus = "reviewing" | "confirmed";
export type Type11 = "optimize_prompt";
export type ThreadId9 = string;
export type NodeId4 = string;
export type Prompt = string;
export type Feedback1 = string;
export type Type12 = "user_message";
export type ThreadId10 = string;
export type Content = string;
export type SelectedNiche = ("baomam_fushi" | "yuer_richang" | "jiating_chufang") | null;
export type Type13 = "error";
export type Code = string;
export type Message = string;
export type BadType = string | null;
export type Type14 = "session_list";
export type Sessions = {
  [k: string]: unknown;
}[];
export type Type15 = "session_state";
export type ThreadId11 = string;
export type Messages = {
  [k: string]: unknown;
}[];
export type Canvas = {
  [k: string]: unknown;
} | null;
export type Type16 = "canvas_updated";
export type ThreadId12 = string;
export type Canvas1 = {
  [k: string]: unknown;
} | null;
export type Type17 = "prompt_optimized";
export type ThreadId13 = string;
export type NodeId5 = string;
export type OptimizedPrompt = string;
export type Type18 = "processing";
export type ThreadId14 = string;
export type Type19 = "agent_stream";
export type ThreadId15 = string;
export type Event = "text" | "tool_call";
export type Content1 = string | null;
export type Name = string | null;
export type Args = string | null;
export type Type20 = "agent_response";
export type ThreadId16 = string;
export type Content2 = string;
export type Canvas2 = {
  [k: string]: unknown;
} | null;
export type Type21 = "analysis_returned";
export type ThreadId17 = string;
export type Type22 = "rewrite_returned";
export type ThreadId18 = string;
export type AnalysisId = string;
export type Type23 = "shot_first_frame_returned";
export type ThreadId19 = string;
export type RewriteId = string;
export type ShotIndex = number;
export type ImageUrl = string;
export type Type24 = "analysis_answer_returned";
export type ThreadId20 = string;
export type AnalysisId1 = string;
export type Question = string;
export type Answer = string;
export type Type25 = "analysis_failed";
export type ThreadId21 = string;
export type Code1 = string;
export type Hint = string;
export type Actions = string[];
export type RequestId = string;
export type Stage = string;

export interface WSMessages {
  WSInbound?:
    | AuthMsg
    | ListSessionsMsg
    | DeleteSessionMsg
    | GetSessionStateMsg
    | ReorderEdgeMsg
    | CreateEdgeMsg
    | DeleteEdgeMsg
    | UpdatePositionMsg
    | ReviewNodeMsg
    | ExecuteNodeMsg
    | UpdateNodeStatusMsg
    | OptimizePromptMsg
    | UserMessageMsg;
  WSOutbound?:
    | ErrorEvent
    | SessionListEvent
    | SessionStateEvent
    | CanvasUpdatedEvent
    | PromptOptimizedEvent
    | ProcessingEvent
    | AgentStreamEvent
    | AgentResponseEvent
    | AnalysisReturnedEvent
    | RewriteReturnedEvent
    | ShotFirstFrameReturnedEvent
    | AnalysisAnswerReturnedEvent
    | AnalysisFailedEvent;
  [k: string]: unknown;
}
export interface AuthMsg {
  type: Type;
  user_id: UserId;
  invite_code?: InviteCode;
}
export interface ListSessionsMsg {
  type: Type1;
}
export interface DeleteSessionMsg {
  type: Type2;
  thread_id: ThreadId;
}
export interface GetSessionStateMsg {
  type: Type3;
  thread_id: ThreadId1;
}
export interface ReorderEdgeMsg {
  type: Type4;
  thread_id: ThreadId2;
  edge_id: EdgeId;
  direction?: Direction;
}
export interface CreateEdgeMsg {
  type: Type5;
  thread_id: ThreadId3;
  source: Source;
  target: Target;
}
export interface DeleteEdgeMsg {
  type: Type6;
  thread_id: ThreadId4;
  edge_id: EdgeId1;
}
export interface UpdatePositionMsg {
  type: Type7;
  thread_id: ThreadId5;
  node_id: NodeId;
  x: X;
  y: Y;
}
export interface ReviewNodeMsg {
  type: Type8;
  thread_id: ThreadId6;
  node_id: NodeId1;
  action: Action;
  feedback?: Feedback;
}
export interface ExecuteNodeMsg {
  type: Type9;
  thread_id: ThreadId7;
  node_id: NodeId2;
  node_type: NodeType;
  description?: Description;
  image_gen_provider?: ImageGenProvider;
  duration?: Duration;
  resolution?: Resolution;
  generate_audio?: GenerateAudio;
}
export interface UpdateNodeStatusMsg {
  type: Type10;
  thread_id: ThreadId8;
  node_id: NodeId3;
  node_status?: NodeStatus;
}
export interface OptimizePromptMsg {
  type: Type11;
  thread_id: ThreadId9;
  node_id: NodeId4;
  prompt: Prompt;
  feedback: Feedback1;
}
export interface UserMessageMsg {
  type: Type12;
  thread_id: ThreadId10;
  content: Content;
  selected_niche?: SelectedNiche;
}
export interface ErrorEvent {
  type: Type13;
  code: Code;
  message: Message;
  bad_type?: BadType;
}
export interface SessionListEvent {
  type: Type14;
  sessions: Sessions;
}
export interface SessionStateEvent {
  type: Type15;
  thread_id: ThreadId11;
  messages: Messages;
  canvas?: Canvas;
}
export interface CanvasUpdatedEvent {
  type: Type16;
  thread_id: ThreadId12;
  canvas?: Canvas1;
}
export interface PromptOptimizedEvent {
  type: Type17;
  thread_id: ThreadId13;
  node_id: NodeId5;
  optimized_prompt: OptimizedPrompt;
}
export interface ProcessingEvent {
  type: Type18;
  thread_id: ThreadId14;
}
export interface AgentStreamEvent {
  type: Type19;
  thread_id: ThreadId15;
  event: Event;
  content?: Content1;
  name?: Name;
  args?: Args;
}
export interface AgentResponseEvent {
  type: Type20;
  thread_id: ThreadId16;
  content: Content2;
  canvas?: Canvas2;
}
/**
 * Pushed by `cascade_analyze` tool after upstream analysis succeeds.
 *
 * Carries the full `CascadeAnalysisContract.model_dump()` so the frontend
 * CardStack can render ScriptCard/ShotCard immediately without an extra
 * HTTP round-trip.
 */
export interface AnalysisReturnedEvent {
  type: Type21;
  thread_id: ThreadId17;
  analysis: Analysis;
}
export interface Analysis {
  [k: string]: unknown;
}
/**
 * Pushed by `cascade_rewrite` tool after niche rewrite succeeds.
 *
 * Carries `RewriteResult.model_dump()` plus the originating analysis_id so
 * the frontend can correlate the rewrite back to its source analysis card.
 */
export interface RewriteReturnedEvent {
  type: Type22;
  thread_id: ThreadId18;
  analysis_id: AnalysisId;
  rewrite: Rewrite;
}
export interface Rewrite {
  [k: string]: unknown;
}
/**
 * Pushed by `cascade_generate_first_frame` after a per-shot image succeeds.
 *
 * Frontend matches `shot_index` against `shots[].scene_index` and patches in
 * `image_url` so the matching ShotCard re-renders without a full payload
 * refresh.
 */
export interface ShotFirstFrameReturnedEvent {
  type: Type23;
  thread_id: ThreadId19;
  rewrite_id: RewriteId;
  shot_index: ShotIndex;
  image_url: ImageUrl;
}
/**
 * Pushed by `cascade_ask` after a free-form Q&A LLM call succeeds.
 *
 * Carries the analysis_id + the user's question + the bounded (~300 char)
 * answer so the frontend chat panel can render a styled bubble (or, in
 * Phase 1, just chat-relay it via the Director's reply).
 */
export interface AnalysisAnswerReturnedEvent {
  type: Type24;
  thread_id: ThreadId20;
  analysis_id: AnalysisId1;
  question: Question;
  answer: Answer;
}
/**
 * W5D3 — structured failure push (replaces fragile chat-message heuristic).
 *
 * Whenever the agent runner / cascade tool catches a HardFailure or unhandled
 * exception in the analysis path, push this frame so the frontend can flip
 * ChatPanel into `failed` state directly. `payload` mirrors FailurePayload
 * in frontend/src/types/cascade.ts (code / hint / actions / request_id).
 */
export interface AnalysisFailedEvent {
  type: Type25;
  thread_id: ThreadId21;
  code: Code1;
  hint: Hint;
  actions?: Actions;
  request_id?: RequestId;
  stage?: Stage;
}
