/* AUTO-GENERATED by scripts/sync-ws-types.sh — DO NOT EDIT.\n   Source: backend/src/agent/transport/ws_messages.py */

export type Type = "auth";
export type UserId = string;
export type Type1 = "list_sessions";
export type Type2 = "delete_session";
export type ThreadId = string;
export type Type3 = "get_session_state";
export type ThreadId1 = string;
export type Type4 = "reorder_edge";
export type ThreadId2 = string;
export type EdgeId = string;
export type Direction = "up" | "down";
export type Type5 = "create_edge";
export type ThreadId3 = string;
export type Source = string;
export type Target = string;
export type Type6 = "delete_edge";
export type ThreadId4 = string;
export type EdgeId1 = string;
export type Type7 = "update_position";
export type ThreadId5 = string;
export type NodeId = string;
export type X = number;
export type Y = number;
export type Type8 = "review_node";
export type ThreadId6 = string;
export type NodeId1 = string;
export type Action = "approve" | "reject";
export type Feedback = string | null;
export type Type9 = "execute_node";
export type ThreadId7 = string;
export type NodeId2 = string;
export type NodeType = "script" | "image" | "video" | "composite";
export type Description = string;
export type ImageGenProvider = string | null;
export type Duration = number | null;
export type Resolution = string | null;
export type GenerateAudio = boolean | null;
export type Type10 = "update_node_status";
export type ThreadId8 = string;
export type NodeId3 = string;
export type NodeStatus = "reviewing" | "confirmed";
export type Type11 = "optimize_prompt";
export type ThreadId9 = string;
export type NodeId4 = string;
export type Prompt = string;
export type Feedback1 = string;
export type Type12 = "user_message";
export type ThreadId10 = string;
export type Content = string;
export type Type13 = "error";
export type Code = string;
export type Message = string;
export type BadType = string | null;
export type Type14 = "session_list";
export type Sessions = {
  [k: string]: unknown;
}[];
export type Type15 = "session_state";
export type ThreadId11 = string;
export type Messages = {
  [k: string]: unknown;
}[];
export type Canvas = {
  [k: string]: unknown;
} | null;
export type Type16 = "canvas_updated";
export type ThreadId12 = string;
export type Canvas1 = {
  [k: string]: unknown;
} | null;
export type Type17 = "prompt_optimized";
export type ThreadId13 = string;
export type NodeId5 = string;
export type OptimizedPrompt = string;
export type Type18 = "processing";
export type ThreadId14 = string;
export type Type19 = "agent_stream";
export type ThreadId15 = string;
export type Event = "text" | "tool_call";
export type Content1 = string | null;
export type Name = string | null;
export type Args = string | null;
export type Type20 = "agent_response";
export type ThreadId16 = string;
export type Content2 = string;
export type Canvas2 = {
  [k: string]: unknown;
} | null;

export interface WSMessages {
  WSInbound?:
    | AuthMsg
    | ListSessionsMsg
    | DeleteSessionMsg
    | GetSessionStateMsg
    | ReorderEdgeMsg
    | CreateEdgeMsg
    | DeleteEdgeMsg
    | UpdatePositionMsg
    | ReviewNodeMsg
    | ExecuteNodeMsg
    | UpdateNodeStatusMsg
    | OptimizePromptMsg
    | UserMessageMsg;
  WSOutbound?:
    | ErrorEvent
    | SessionListEvent
    | SessionStateEvent
    | CanvasUpdatedEvent
    | PromptOptimizedEvent
    | ProcessingEvent
    | AgentStreamEvent
    | AgentResponseEvent;
  [k: string]: unknown;
}
export interface AuthMsg {
  type: Type;
  user_id: UserId;
}
export interface ListSessionsMsg {
  type: Type1;
}
export interface DeleteSessionMsg {
  type: Type2;
  thread_id: ThreadId;
}
export interface GetSessionStateMsg {
  type: Type3;
  thread_id: ThreadId1;
}
export interface ReorderEdgeMsg {
  type: Type4;
  thread_id: ThreadId2;
  edge_id: EdgeId;
  direction?: Direction;
}
export interface CreateEdgeMsg {
  type: Type5;
  thread_id: ThreadId3;
  source: Source;
  target: Target;
}
export interface DeleteEdgeMsg {
  type: Type6;
  thread_id: ThreadId4;
  edge_id: EdgeId1;
}
export interface UpdatePositionMsg {
  type: Type7;
  thread_id: ThreadId5;
  node_id: NodeId;
  x: X;
  y: Y;
}
export interface ReviewNodeMsg {
  type: Type8;
  thread_id: ThreadId6;
  node_id: NodeId1;
  action: Action;
  feedback?: Feedback;
}
export interface ExecuteNodeMsg {
  type: Type9;
  thread_id: ThreadId7;
  node_id: NodeId2;
  node_type: NodeType;
  description?: Description;
  image_gen_provider?: ImageGenProvider;
  duration?: Duration;
  resolution?: Resolution;
  generate_audio?: GenerateAudio;
}
export interface UpdateNodeStatusMsg {
  type: Type10;
  thread_id: ThreadId8;
  node_id: NodeId3;
  node_status?: NodeStatus;
}
export interface OptimizePromptMsg {
  type: Type11;
  thread_id: ThreadId9;
  node_id: NodeId4;
  prompt: Prompt;
  feedback: Feedback1;
}
export interface UserMessageMsg {
  type: Type12;
  thread_id: ThreadId10;
  content: Content;
}
export interface ErrorEvent {
  type: Type13;
  code: Code;
  message: Message;
  bad_type?: BadType;
}
export interface SessionListEvent {
  type: Type14;
  sessions: Sessions;
}
export interface SessionStateEvent {
  type: Type15;
  thread_id: ThreadId11;
  messages: Messages;
  canvas?: Canvas;
}
export interface CanvasUpdatedEvent {
  type: Type16;
  thread_id: ThreadId12;
  canvas?: Canvas1;
}
export interface PromptOptimizedEvent {
  type: Type17;
  thread_id: ThreadId13;
  node_id: NodeId5;
  optimized_prompt: OptimizedPrompt;
}
export interface ProcessingEvent {
  type: Type18;
  thread_id: ThreadId14;
}
export interface AgentStreamEvent {
  type: Type19;
  thread_id: ThreadId15;
  event: Event;
  content?: Content1;
  name?: Name;
  args?: Args;
}
export interface AgentResponseEvent {
  type: Type20;
  thread_id: ThreadId16;
  content: Content2;
  canvas?: Canvas2;
}
