#!/usr/bin/env bash
# Regenerate frontend WS types from backend Pydantic models.
#
# Pipeline:
#   backend Pydantic (ws_messages.py) ──┐
#                                       ▼
#         export_ws_schema.py ──► frontend/scripts/ws_schema.json
#                                       │
#                                       ▼
#                          json2ts (json-schema-to-typescript)
#                                       │
#                                       ▼
#                      frontend/src/types/ws_generated.ts
#
# Run after editing backend/src/agent/transport/ws_messages.py.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCHEMA="$REPO_ROOT/frontend/scripts/ws_schema.json"
GENERATED="$REPO_ROOT/frontend/src/types/ws_generated.ts"

echo "[sync-ws-types] exporting JSON Schema from Pydantic…"
mkdir -p "$REPO_ROOT/frontend/scripts"
(cd "$REPO_ROOT/backend" && uv run python scripts/export_ws_schema.py) > "$SCHEMA"

echo "[sync-ws-types] generating TS via json2ts…"
(cd "$REPO_ROOT/frontend" && npx --yes json-schema-to-typescript@latest \
    --input scripts/ws_schema.json \
    --output src/types/ws_generated.ts \
    --bannerComment "/* AUTO-GENERATED by scripts/sync-ws-types.sh — DO NOT EDIT.\n   Source: backend/src/agent/transport/ws_messages.py */")

echo "[sync-ws-types] done. Modified:"
echo "  $SCHEMA"
echo "  $GENERATED"
