export const COPY = {
  script_header: "改完的版本",
  shots_header: "镜头草稿",
  publish_header: "准备发出去",
  hook_label: "开头怎么抓人",
  pacing_label: "中间为什么不快进",
  climax_label: "结尾为什么忍不住点赞",
  shot_label_prefix: "第",
  shot_label_suffix: "段",
  shot_dialogue_placeholder: "（这段没有台词，是画面）",
  anchor_picker_title: "你之前用过的",
  anchor_character_label: "角色",
  anchor_scene_label: "场景",
  copy_button: "一键复制，去发",
  copy_success: "复制好了，去抖音粘贴吧",
  empty_state:
    "还没有分析内容。在左侧聊天里发一条爆款链接，或从今日精选里挑一条。",
  low_confidence_banner: "系统对这条分析的把握一般，仅供参考",
  why_viral_header: "为什么这条会火",
  change_character: "换个角色",
  reuse_scene: "用我之前的场景",
  edit_script: "改一改",
  save_script: "保存",
  pro_view_label: "流程视图",
  card_view_label: "卡片视图",
  suggested_titles: "标题备选",
  tags_label: "话题标签",
} as const;

/** Terms that must never appear in card-stack UI copy or DOM. */
export const FORBIDDEN_TERMS = [
  "节点",
  "锚点",
  "DAG",
  "agent",
  "Agent",
  "画布",
  "AI",
  "平台",
  "工具",
  "智能",
  "pipeline",
  "workflow",
] as const;
